# Generated by Django 3.1.1 on 2020-09-30 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast_or_roast', models.BooleanField(default=False)),
                ('post', models.CharField(max_length=500)),
                ('up_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('down_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
