# Generated by Django 3.1.1 on 2020-10-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201001_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
